CLASS zbp_ir_scort_obj_t DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zir_scort_obj_t.

  "! Behavior Pool for ZIR_SCORT_OBJ_T (auto-generated by RAP Engine).
  "! Read-only entity: CCIMP is intentionally empty.
  "! No custom actions or validations needed.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_ir_scort_obj_t IMPLEMENTATION.
  "-- Empty: RAP Engine handles all read operations via CDS framework.
ENDCLASS.
