CLASS zbp_ir_scort_obj_l DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zir_scort_obj_l.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_ir_scort_obj_l IMPLEMENTATION.

ENDCLASS.
